ecommerce/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from newsletter.views import contact, home
from ecommerce.views import about
from carts.views import (
    CartView,
    ItemCountView,
    CheckoutView,
    CheckoutFinalView
)
from orders.views import (
    AddressSelectFormView,
    UserAddressCreateView,
    OrderList,
    OrderDetail
)

urlpatterns = [
    # Examples:
    url(r'^$', home, name='home'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^about/$', about, name='about'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^categories/', include('products.urls_categories', namespace='categories')),

    url(r'^orders/$', OrderList.as_view(), name='orders'),
    url(r'^orders/(?P<pk>\d+)/$', OrderDetail.as_view(), name='order_detail'),
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^cart/count$', ItemCountView.as_view(), name='item_count'),
    url(r'^checkout/$', CheckoutView.as_view(), name='checkout'),
    url(r'^checkout/address/$', AddressSelectFormView.as_view(), name='order_address'),
    url(r'^checkout/address/add/$', UserAddressCreateView.as_view(), name='user_address_create'),
    url(r'^checkout/final/$', CheckoutFinalView.as_view(), name='checkout_final'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from products.views import ProductDetailView, ProductListView, VariationListView

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/inventory/$', VariationListView.as_view(), name='inventory'),
]

templates/about.html
{% extends "base.html" %}



{% block content %}

<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1>About Us</h1>
<p>This is about us. This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.</p>
<p>This is about us. This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.</p>
<p>This is about us. This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.This is about us.</p>
</div>

</div>


{% endblock %}

templates/alert.html
<div class='container container-alert-flash'><div class='col-sm-3 col-sm-offset-8'><div class='alert alert-{{ type }} alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>{{ message }}</div></div></div>

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">

        <title>{% block head_title %}eCommerce 2{% endblock %}</title>

        {% include 'head_css.html' %}

        <style>
            {% block style %}{% endblock %}
        </style>
    </head>

    <body>
        {% include 'navbar.html' %}
        {% include 'messages.html' %}

        {% block jumbotron %}
          
        {% endblock jumbotron %}

        <div class="container">
            {% block content %}
            {% endblock %}
        </div> <!-- /container -->

        {% include "javascript.html" %}

        <script>
            $(document).ready(function(){
                {% block jquery %}

                {% endblock jquery %}
            });
        </script>
    </body>

</html>

templates/example_fluid.html
{% extends "base.html" %}

{% block jumbotron %}
_
{% endblock %}

{% block content %}

<div class="row">
<div class="col-sm-3" style='background-color:orange;'>




             .col-md-4



             </div>

</div>

<div class="row">
  <div class="col-md-8 col-sm-6" style='background-color:red;'>.col-md-8
        <div class="row">
             <div class="col-md-6 col-sm-8 col-xs-2" style='background-color:orange;'>




             .col-md-4



             </div>
            <div class="col-md-6 col-sm-4 col-xs-10" style='background-color:yellow;'>.col-md-4</div>

        </div>

  </div>
  <div class="col-md-4 col-sm-6" style='background-color:blue;'>.col-md-4

    <div class="row">
             <div class="col-md-12" style='background-color:purple;'>.col-md-4</div>

        </div>

    </div>
</div>
<!-- <div class="row">
  <div class="col-md-4">.col-md-4</div>
  <div class="col-md-4">.col-md-4</div>
  <div class="col-md-4">.col-md-4</div>
</div>
<div class="row">
  <div class="col-md-6">.col-md-6</div>
  <div class="col-md-6">.col-md-6</div>
</div> -->

{% endblock %}

templates/forms.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}





<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>


{% if title %}
<h1 class='{% if title_align_center %}text-align-center{% endif %}'>{{ title }}</h1>
{% endif %}

<form method='POST' action=''>{% csrf_token %}
{{ form|crispy }}

<input class='btn btn-default' type='submit' value='Submit' />

</form>
</div>
</div>
{% endblock %}

templates/head_css.html
{% load staticfiles %}
    <!-- Bootstrap core CSS -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet"> -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/> -->
    <!-- Custom styles for this template -->
    <!-- <link href="navbar-static-top.css" rel="stylesheet"> -->
    <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">
     <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}


{% block head_title %}Welcome | {{ block.super }}{% endblock %}

<style>
{% block style %}
.navbar-static-top {
	margin-bottom: 0px !important;
}

.jumbotron {
	background-color:#5ACDFF;
	color: #000;
    text-shadow: 2px 2px 8px #333333;
    {% if featured_image.make_image_background %}
        background-image: url("{{ featured_image.image.url }}");
        background-repeat: no-repeat;
        background-color: black;
        background-size: 100% 100%;

        {% if featured_image.text_css_color %}
            color: #{{ featured_image.text_css_color }}
        {% endif %}
    {% endif %}
}

{% endblock %}
</style>


{% block jumbotron %}
    {% if featured_image %}
        <div class="jumbotron">
            <div class="container">
                <div class="row">
                    <div class='{% if featured_image.make_image_background %}col-sm-12 text-center {% else %}col-sm-6{% endif %}{% if featured_image.text_right %}pull-right{% endif %}'>
                        <h1>{{ featured_image.product.title }}</h1>
                        <p>{{ featured_image.product.description }}</p>
                        <p>
                            <a style="opacity: 0.8" class="btn btn-lg btn-default" href="{{ featured_image.product.get_absolute_url }}" role="button">
                                More Details
                            </a>
                        </p>
                    </div>
                    {% if not featured_image.make_image_background %}
                    <div class='col-sm-6' >
                        <img class="img-responsive" src="{{ featured_image.image.url }}" alt="{{ featured_image.product.title }}" />
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% else %}
        <div class="jumbotron">
            <div class="container">
                <div class="row">
                    <div class='col-sm-12'>
                    <h1>eCommerce</h1>
                    <p>
                        The eCommerce project is designed to get your project started.
                        The goal is to help you launch as soon as possible with the least amount
                        of investment using time or money.
                    </p>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}




{% block content %}
    <div class="row">
        <h3>Recommended Products</h3>
        {% include "products/products.html" with object_list=products col_class_set="col-xs-2" %}
    </div>
    <div class="row">
        <h3>Featured Products</h3>
        {% include "products/products.html" with object_list=products2 %}
    </div>

{##}
{#    {% if request.user.is_authenticated %}#}
{#        <h1>You are logged in!</h1>#}
{##}
{#        {% if queryset %}#}
{#        <h2>Welcome Staff</h2>#}
{#        <table class='table'>#}
{#        {% for instance in queryset %}#}
{#            <tr><td>{{ forloop.counter }}</td><td>{{ instance.email }}</td><td>{{ instance.full_name }}</td><td>{{ instance.timestamp|timesince }} ago</td></tr>#}
{#            {% if instance.email == "abc@gmail.edu" %}#}
{#            <tr><td>is equal</td></tr>#}
{#            {% endif %}#}
{#        {% endfor %}#}
{#        </table>#}
{##}
{#        {% endif %}#}
{#    {% else %}#}
{#        <div class="row">#}
{##}
{#            <div class="col-sm-3 pull-right">#}
{#                <p class='lead text-align-center'>{{ title }}</p>#}
{##}
{#                <form method='POST' action=''>{% csrf_token %}#}
{#                    {{ form|crispy }}#}
{#                    <input class='btn btn-primary' type='submit' value='Sign Up' />#}
{#                </form>#}
{#            </div>#}
{##}
{#            <div class='col-sm-3'>#}
{#                <p class='lead text-align-center'>Django &amp; Bootstrap</p>#}
{#                <img src='{% static "img/marketing1.jpg" %}' class='img-responsive' />#}
{#            </div>#}
{##}
{#            <div class='col-sm-3'>#}
{#                <p class='lead text-align-center'>#}
{#                    Created for Starters<br/>#}
{#                    <span class='fa-stack fa-lg fa-5x'>#}
{#                        <i class='fa fa-comment-o fa-stack-2x'></i>#}
{#                        <i style='color:yellow;' class="fa fa-bolt fa-stack-1x"></i>#}
{#                    </span>#}
{#                </p>#}
{#            </div>#}
{##}
{#            <div class='col-sm-3'>#}
{#                <p class='lead text-align-center'>#}
{#                    Always Open Source<br/><br/>#}
{#                    <span class="fa-stack fa-lg fa-5x">#}
{#                        <i class="fa fa-circle-o-notch fa-stack-2x"></i>#}
{#                        <!-- <i class="fa fa-square-o fa-stack-2x"></i> -->#}
{#                        <i class="fa fa-github fa-stack-1x"></i>#}
{#                    </span>#}
{#                </p>#}
{#            </div>#}
{#        </div>#}
{#    {% endif %}#}
{% endblock %}

templates/javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

    <script>
        function updateCartItemCount(){
            var badge = $("#cart-count-badge");
            $.ajax({
                type: "GET",
                url: "{% url 'item_count' %}",
                success: function(data){
                    badge.text(data.count);
                },
                error: function(response, error){
                    console.log(response);
                    console.log(error);
                }
            });
        }
        $(document).ready(function(){
            updateCartItemCount();
        })
    </script>

templates/messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
        <div class="alert alert-success">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                {% if "html_safe" in message.tags %}
                    {{ message|safe }}
                {% else %}
                    {{ message }}
                {% endif %}.
            </div>
{#            <strong>Success!</strong> This alert box could indicate a successful or positive action.#}
        </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
   {% load staticfiles %}

   <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">BigDeal</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'home' %}">Home</a></li>

              <form class="navbar-form navbar-left" method="GET" action="{% url "products:list" %}">
                  <div class="form-group">
                      <input type="text" class="form-control" placeholder="Search" name="q" value="{% if query %}{{ query }}{% endif %}">
                  </div>
{#                  <button type="submit" class="btn btn-default">Submit</button>#}
              </form>

{#            <li><a href="{% url 'about' %}">About</a></li>#}
{#            <li><a href="{% url 'contact' %}">Contact</a></li>#}

          </ul>

          <ul class="nav navbar-nav navbar-right">
          <li>
              <a href="{% url 'cart' %}">
                  <i class="fa fa-shopping-cart fa-navbar-cart" aria-hidden="true"></i>
                  <span id="cart-count-badge" class="badge">{{ request.session.cart_item_count }}</span>
              </a>
          </li>
          {% if request.user.is_authenticated %}
              <li><a href="{% url 'orders' %}">Orders</a></li>
            <li><a href="{% url 'auth_logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'registration_register' %}">Register</a></li>
                {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Login <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
{#                            <li><a href="#">Action</a></li>#}
{#                            <li><a href="#">Another action</a></li>#}
{#                            <li><a href="#">Something else here</a></li>#}
{#                            <li class="divider"></li>#}
{#                            <li class="dropdown-header">Nav header</li>#}
{#                            <li><a href="#">Separated link</a></li>#}
{#                            <li><a href="#">One more separated link</a></li>#}

                            <form class='navbar-form' method='POST' action='{% url "auth_login" %}'>{% csrf_token %}
                                <div class='form-group'>
                                    <input type='text' class='form-control' name='username' placeholder='Username' />
                                </div>
                                <div class='form-group'>
                                    <input type='password' class='form-control' name='password' placeholder='Password' />
                                </div>
                                <button type='submit' class='btn btn-default btn-block'>Login</button>
                            </form>
                            <p class="text-center"><a href="{% url "auth_password_reset" %}">Forgot Password</a>?</p>
                        </ul>
                    </li>
                {% endif %}
            {% endif %}
          </ul>

        </div><!--/.nav-collapse -->
      </div>
    </nav>