ecommerce/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from newsletter.views import contact, home
from ecommerce.views import about
from carts.views import (
    CartView,
    ItemCountView,
    CheckoutView,
    CheckoutFinalView
)
from orders.views import (
    AddressSelectFormView,
    UserAddressCreateView,
    OrderList,
    OrderDetail
)

urlpatterns = [
    # Examples:
    url(r'^$', home, name='home'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^about/$', about, name='about'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^categories/', include('products.urls_categories', namespace='categories')),

    url(r'^orders/$', OrderList.as_view(), name='orders'),
    url(r'^orders/(?P<pk>\d+)/$', OrderDetail.as_view(), name='order_detail'),
    url(r'^cart/$', CartView.as_view(), name='cart'),
    url(r'^cart/count$', ItemCountView.as_view(), name='item_count'),
    url(r'^checkout/$', CheckoutView.as_view(), name='checkout'),
    url(r'^checkout/address/$', AddressSelectFormView.as_view(), name='order_address'),
    url(r'^checkout/address/add/$', UserAddressCreateView.as_view(), name='user_address_create'),
    url(r'^checkout/final/$', CheckoutFinalView.as_view(), name='checkout_final'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf.urls import url

from products.views import ProductDetailView, ProductListView, VariationListView

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/inventory/$', VariationListView.as_view(), name='inventory'),
]

products/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from django.utils.text import slugify
from django.utils.text import mark_safe


class ProductQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(active=True)


class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def all(self, *args, **kwargs):
        return self.get_queryset().active()

    def get_related(self, instance):
        products_one = self.get_queryset().filter(categories__in=instance.categories.all())
        products_two = self.get_queryset().filter(default=instance.default)
        qs = (products_one | products_two).exclude(id=instance.id).distinct()
        return qs


class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(decimal_places=2, max_digits=20)
    active = models.BooleanField(default=True)

    # Categories.
    categories = models.ManyToManyField('Category', blank=True)
    default = models.ForeignKey('Category', related_name='default_category', null=True, blank=True)

    # Manager.
    objects = ProductManager()

    class Meta:
        ordering = ['-title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'pk': self.pk})

    def get_image_url(self):
        img = self.productimage_set.first()
        if img:
            return img.image.url
        return img


class Variation(models.Model):
    product = models.ForeignKey(Product)
    title = models.CharField(max_length=120)
    price = models.DecimalField(decimal_places=2, max_digits=20)
    sale_price = models.DecimalField(decimal_places=2, max_digits=20, null=True, blank=True)
    active = models.BooleanField(default=True)
    inventory = models.IntegerField(null=True, blank=True)     # refer none == unlimited amount.

    def __str__(self):
        return self.title

    def get_price(self):
        if self.sale_price is not None:
            return self.sale_price
        else:
            return self.price

    def get_sale_price(self):
        if self.sale_price is not None:
            html_text = """
                <span class='sale-price'>%s</span>
                <span class='og-price'>%s</span>
            """ % (self.sale_price, self.price)

        else:
            html_text = "<span class='price'>%s</span>" % self.price
        return mark_safe(html_text)

    def get_absolute_url(self):
        return self.product.get_absolute_url()

    def add_to_cart(self, qty=1):
        return "%s?item=%s&qty=%s" % (reverse("cart"), self.id, str(qty))

    def remove_from_cart(self):
        return "%s?item=%s&qty=1&delete=true" % (reverse("cart"), self.id)

    def get_title(self):
        return "%s - %s" % (self.product.title, self.title)


def product_save_receiver(sender, instance, created, *args, **kwargs):
    product = instance
    variations = product.variation_set.all()
    if variations.count() == 0:
        new_var = Variation()
        new_var.product = product
        new_var.title = 'Default'
        new_var.price = product.price
        new_var.save()


post_save.connect(product_save_receiver, sender=Product)


def image_upload_to(instance, filename):
    title = instance.product.title
    slug = slugify(title)
    file_extension = filename.split('.')[-1]
    new_filename = "%s.%s" % (instance.id, file_extension)
    return "products/%s/%s" % (slug, new_filename)


class ProductImage(models.Model):
    product = models.ForeignKey(Product)
    image = models.ImageField(upload_to=image_upload_to)

    def __str__(self):
        return self.product.title


# Product Categories

class Category(models.Model):
    title = models.CharField(max_length=120, unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('categories:detail', kwargs={'slug': self.slug})


def image_upload_to_featured(instance, filename):
    title = instance.product.title
    slug = slugify(title)
    file_extension = filename.split('.')[-1]
    new_filename = "%s.%s" % (instance.id, file_extension)
    return "products/%s/featured/%s" % (slug, new_filename)


class ProductFeatured(models.Model):
    product = models.ForeignKey(Product)
    image = models.ImageField(upload_to=image_upload_to_featured)
    title = models.CharField(max_length=120, null=True, blank=True)
    text = models.CharField(max_length=220, null=True, blank=True)
    text_right = models.BooleanField(default=False)
    text_css_color = models.CharField(max_length=6, null=True, blank=True)
    show_price = models.BooleanField(default=False)
    make_image_background = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.product.title

products/forms.py
from django import forms
from django.forms.models import modelformset_factory

from products.models import Variation


class VariationInventoryForm(forms.ModelForm):
    class Meta:
        model = Variation
        fields = [
            # "title",
            "price",
            "sale_price",
            "inventory",
            "active",
        ]

VariationInventoryFormSet = modelformset_factory(Variation, form=VariationInventoryForm, extra=0)

products/views.py
from django.conf import settings
from django.contrib import messages
from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.utils import timezone

from products.models import Product, Variation, Category
from products.forms import VariationInventoryFormSet

from products.mixins import StaffRequiredMixin, LoginRequiredMixin
import random


class CategoryListView(ListView):
    model = Category
    queryset = Category.objects.all()
    template_name = 'products/product_list.html'


class CategoryDetailView(DetailView):
    model = Category

    def get_context_data(self, *args, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(*args, **kwargs)
        obj = self.get_object()
        product_set = obj.product_set.all()
        default_products = obj.default_category.all()
        products = (product_set | default_products).distinct()
        context['products'] = products
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product_detail.html'  # default value.

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        instance = self.get_object()
        # context['related'] = Product.objects.get_related(instance).order_by("?")[:6]
        context['related'] = sorted(Product.objects.get_related(instance)[:6], key=lambda x: random.random())

        return context


class ProductListView(ListView):
    model = Product
    queryset = Product.objects.all()    # default value.
    template_name = 'products/product_list.html'  # default value.

    def get_context_data(self, *args, **kwargs):    # to add something to context variable.
        context = super(ProductListView, self).get_context_data(*args, **kwargs)
        context['now'] = timezone.now()
        context['query'] = self.request.GET.get('q', None)
        return context

    def get_queryset(self, *args, **kwargs):
        qs = super(ProductListView, self).get_queryset(*args, **kwargs)
        query = self.request.GET.get("q")
        if query:
            qs = self.model.objects.filter(
                Q(title__icontains=query) |
                Q(description__icontains=query)
            )
            try:
                qs2 = self.model.objects.filter(
                    Q(price=query)
                )
                qs = (qs | qs2).distinct()
            except:
                pass
        return qs


class VariationListView(StaffRequiredMixin, ListView):
    model = Product
    queryset = Variation.objects.all()    # default value.
    template_name = 'products/variation_list.html'  # default value.

    def get_context_data(self, *args, **kwargs):    # to add something to context variable.
        context = super(VariationListView, self).get_context_data(*args, **kwargs)
        context['formset'] = VariationInventoryFormSet(queryset=self.get_queryset())
        return context

    def get_queryset(self, *args, **kwargs):
        product_pk = self.kwargs.get("pk")
        queryset = None
        if product_pk:
            product = get_object_or_404(Product, pk=product_pk)
            queryset = Variation.objects.filter(product=product)
        return queryset

    def post(self, request, *args, **kwargs):
        formset = VariationInventoryFormSet(request.POST, request.FILES)

        if formset.is_valid():
            formset.save(commit=False)
            for form in formset:
                new_item = form.save(commit=False)
                # if new_item.title:
                product_pk = self.kwargs.get('pk')
                product = get_object_or_404(Product, pk=product_pk)
                new_item.product = product
                new_item.save()

            html_message = '''
                <strong>Your inventory and pricing has been updated.</strong>
            '''
            html_message = settings.MESSAGE % ('success', html_message)
            messages.success(request, html_message, extra_tags='html_safe')

            return redirect("products:list")
        raise Http404

products/templates/products/category_detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="row">
        {% for product in products %}

            <div class="col-xs-4">
                {% include "products/product_thumbnail.html" with product=product price="true"%}
            </div>
            {% cycle '' '' '</div><div class="row">' %}

        {% endfor %}
    </div>
{% endblock content %}

products/templates/products/product_detail.html
{% extends "base.html" %}


<script>
    {% block jquery %}

        function setPrice(){
            var price = $(".variation_select option:selected").attr("data-price");
            var sale_price = $(".variation_select option:selected").attr("data-sale-price");
            if(sale_price != "" && sale_price != "None" && sale_price != null){
                $("#price").html("<h3>" + sale_price + " <small class='og-price'>" + price + "</small>" + "</h3>");
            }
            else{
                $("#price").text(price);
            }
        }
        setPrice();
        $(".variation_select").change(function(){
            setPrice();
        });

        $("#submit-btn").click(function(event){
            event.preventDefault();
            var formData = $("#add-form").serialize();
            // console.log(formData);
            $.ajax({
                type: "GET", //"POST"
                url: "{% url 'cart' %}",
                data: formData,
                success: function(data){
                    showFlashMessage(data.flash_message, data.message_type);
                    updateCartItemCount();
                },
                error: function(response, error){
                    // console.log(response);
                    // console.log(error);
                }
            });
            // $("#add-form").submit();
        });
    {% endblock jquery %}
</script>


{% block content %}

    <div class="row">
        <div class="col-sm-8">
            <h2>{{ object.title }}</h2>

            {% if object.productimage_set.count > 0 %}
            <div>
            {% for img in object.productimage_set.all %}
                {#                {{ img.image.url }} {{ img.image }} {{ img.image.file }}#}
                <img class="img-responsive" src="{{ img.image.url }}"/>
            {% endfor %}
            </div>
            {% endif %}
            <p class="lead">{{ object.description }}</p>
        </div>
        <!-- Product Sidebar -->
        <div class="col-sm-4">

            <form id="add-form" method="GET" action="{% url 'cart' %}">

                {% if object.variation_set.count > 1 %}
                    <h3 id="price">{{ object.variation_set.first.price }}</h3>
                    <select name="item" class='form-control variation_select'>
                        {% for vari_obj in object.variation_set.all %}
                            <option data-sale-price="{{ vari_obj.sale_price }}" data-price="{{ vari_obj.price }}" value="{{ vari_obj.id }}">{{ vari_obj }}</option>
                        {% endfor %}
                    </select>

                {% else %}
                    <input name="item" type="hidden" value="{{ object.variation_set.first.id }}"/>
                    <h3 id="price">
                        {% if object.variation_set.first.sale_price %}
                            <h3>
                                {{ object.variation_set.first.sale_price }}
                                <small class="og-price">{{ object.variation_set.first.price }}</small>
                            </h3>
                        {% else %}
                            <h3>{{ object.variation_set.first.price }}</h3>
                        {% endif %}
                    </h3>
                {% endif %}
                <br/>
                <input class="form-control" type="number" name="qty" value="1" />
                <br/>
                <input id="submit-btn" type="submit" class="btn btn-sm btn-default" value="Add to Cart"/>
            </form>

            <br/>
            <hr/>
            <p>
                <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
                    <i class="fa fa-facebook-square fa-3x" aria-hidden="true"></i>
                </a>
                <a>
                    <i class="fa fa-twitter-square fa-3x" aria-hidden="true"></i>
                </a>
            </p>
            <hr/>
            <h4>Related Products</h4>
            <div class="row">
                {% for product in related %}
                    <div class="col-xs-6">
                        {% include "products/product_thumbnail.html" with product=product price="true"%}
                    </div>
                    {% cycle '' '</div><div class="row">' %}
                {% endfor %}
            </div>
        </div>
        <!-- End Product Sidebar -->
    </div>


{% endblock %}

products/templates/products/product_list.html
{% extends "base.html" %}



{% block content %}
    <h1>All Products<small><a href="{% url 'categories:list' %}">Categories</a></small></h1>
    {% include "products/products.html" with object_list=object_list %}
{% endblock %}

products/templates/products/product_thumbnail.html
<div class="thumbnail text-center">
    <h4><a href='{{ product.get_absolute_url }}'>{{ product.title }}</a></h4>
    {% if product.get_image_url %}
        <img class="img-responsive" src="{{ product.get_image_url }}" alt="{{ product.title }}"/><br/>
    {% endif %}
    <div class="caption">
        {% if price == "true" %}
            {{ product.variation_set.first.get_sale_price }}
        {% endif %}
    </div>
</div>

products/templates/products/products.html
<div class="row">
    {% for product in object_list %}

        <div class="col-xs-4 {{ col_class_set }}">
            {% include "products/product_thumbnail.html" with product=product price="true"%}
        </div>

        {% if not col_class_set %}
            {% cycle '' '' '</div><div class="row">' %}
        {% endif %}
    {% endfor %}
</div>

products/templates/products/variation_list.html
{% extends "base.html" %}



{% block content %}


    <table class='table'>
        {% for object in object_list %}

            <tr>
                <td><a href='{{ object.get_absolute_url }}'>{{ object.title }}</a></td>
                <td>{{ object.inventory }}</td>
            </tr>

        {% endfor %}
    </table>

    <form method="POST" action="">{% csrf_token %}
{#        {{ formset.as_p }}#}
        {{ formset.management_form }}
        {% for form in formset %}
            <h4>
            {{ form.instance.product.title }}
            {{ form.instance.title }}
            </h4>
            {{ form.as_p }}
            <hr>
        {% endfor %}
    <input type="submit" class="btn btn-bm btn-primary" value="Update" />
    </form>

{% endblock %}